### ISSUE TITLE
How to run DoubletDecon UI with Shiny ?

### ISSUE THREAD

**Issue by ChaDuss** [EDePasquale/DoubletDecon#14]
Hello, 
Thank you for your great package.
How can i lauch the doubletdecon Shiny app in Rstudio ?
Sorry but i'm kind of knew with R and github and i can't fine in the github repository the coorect file to lauch in Rstudio.

Thanks for your answer

Charles

**Comment by Tushar-87** [comment]
I have the same question...

**Comment by EDePasquale** [comment]
Great question!

On the project page for DoubletDecon (https://github.com/EDePasquale/DoubletDecon) select "clone or download" and then "download ZIP". When this is finished, decompress the file. Within this folder, doublet clicking on the "DoubletDecon" application file should open R for you as well as a web browser with the DoubletDecon user interface. I use this because it gives me a DoubletDecon icon I can add to my hot bar for easy access. 

I'm unsure if this works for Windows machines, but if it doesn't or if you don't want the clickable button run the following line in R or R Studio:

`shiny::runGist('a81cdc2aea5742c08e5fc3fa66d47698', launch.browser=TRUE)`

I am working of writing a full protocol for running DoubletDecon both from the command line and the user interface, with pre-processing and analysis steps, which will hopefully be submitted soon!

Please let me know if you have any more questions.

Thanks,
Erica
