### ISSUE TITLE
Error at "combining similar clusters"

### ISSUE THREAD

**Issue by daccachejoe** [EDePasquale/DoubletDecon#24]
Hi I have an error at the combining similar clusters step of the main function. The error comes as part of a loop I have set at the 11th iteration of the code. The first 10 loops work perfectly but with the 11th object, it produces this error:

Error in (function (side, at = NULL, labels = TRUE, tick = TRUE, line = NA,  : 
  no locations are finite
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘mygene’

I've looked within the underlying code and can't find this error message so any help with this would be greatly appreciated.

**Comment by EDePasquale** [comment]
Hi jad362,

Could I get a little clarification on what you are trying to do with your looping? Are you running DoubletDecon multiple times with the exact same settings or are you altering some of the parameters? The first error you are getting is usually caused by the rhop value being set too high, so I would recommend a lower value. 

P.S. Once this error is resolved you may also want to check on the status of your 'mygene' package as it is looking like you don't have that installed (which is interesting because it should be automatically installed on your first run of DoubletDecon).

**Comment by daccachejoe** [comment]
Hi, I'm looping different Seurat objects through the same parameters to test the package out. It seems to work for the first ten objects, but not with the 11th. They were all preprocessed in the same manner so there shouldn't be anything inherently different about the object types. When trying it on yet another similarly processed Seurat object, I got this error:

Error in .External.graphics(C_layout, num.rows, num.cols, mat, as.integer(num.figures),  : 
  invalid graphics state
Error in par(op) : invalid value specified for graphical parameter "pin"

Where can I download the mygene package? Thanks for the help!

**Comment by daccachejoe** [comment]
I'm not really sure what was going wrong with it earlier but I reinstalled both Seurat and DoubletDecon and changed the rhop value from 1.1 to .9 which worked. Thank you!
