### ISSUE TITLE
no locations are finite

### ISSUE THREAD

**Issue by rahulnutron** [EDePasquale/DoubletDecon#45]
Dear DoubletDecon team,

I am using a standard pipeline and Seurat object to identify doublets and keep getting this error

Error in (function (side, at = NULL, labels = TRUE, tick = TRUE, line = NA,  : 
  no locations are finite
In addition: Warning messages:
1: In if (class(groupsFile) == "character") { :
  the condition has length > 1 and only the first element will be used
2: In is.numeric(trim) :
 closing unused connection 3 (D:/DS/data_3/Sample_3.log)

I also reinstall the package, but got the same error, will be grateful if you can suggest me how to fix it.

Regards,
Rahul

**Comment by EDePasquale** [comment]
Hi Rahul,

Please check out the troubleshooting section of my DoubletDecon protocol found here: [https://www.sciencedirect.com/science/article/pii/S2666166720300721?via%3Dihub](https://www.sciencedirect.com/science/article/pii/S2666166720300721?via%3Dihub)

The relevant text is:
"Problem 1

You are receiving a “no locations are finite” error or output to the terminal stating “Unable to perform mcl function for blacklist clustering, please try a different rhop.” when running DoubletDecon.

Potential Solution

This error most commonly occurs when the value you selected for the cluster merging parameter ρ' (‘rhop’ in the parameter list) causes too much or too little merging of the clusters, leading to an error in the Markov clustering portion of the algorithm. Altering the value of this parameter according to the instructions given in Step 3: Determining the cluster merging parameter (ρ') of this protocol should solve the issue, though incrementally stepping down from the ρ' you are currently using (i.e. 1.1 to 1 to 0.9, etc.) will allow you to manually find the upper limit of acceptable ρ' values. Alternatively, the DoubletDecon UI has a built-in function for displaying the merging results for all possible values of ρ' to make it easier to choose an appropriate value within in the range. Once selected, make sure to evaluate the appropriateness of the clustering and adjust up or down depending on whether you want less or more cluster merging, respectively."

Additionally, this issue is covered in the "Determining the cluster merging parameter (ρ')" of the Wiki located in this GitHub repository: [https://github.com/EDePasquale/DoubletDecon/wiki/DoubletDecon-Vignette-with-Dexmulet-Data](https://github.com/EDePasquale/DoubletDecon/wiki/DoubletDecon-Vignette-with-Dexmulet-Data)  

Best,
Erica

**Comment by rahulnutron** [comment]
Thanks! I checked the section. I adjusted the rhop and then its working.
